In [1]:
import pandas as pd

In [20]:
my_df = pd.read_csv('/Users/sianteesdale/Documents/GitHub/local-plan-extractor/dataset/local-plan.csv')

old_df = pd.read_csv('/Users/sianteesdale/Documents/GitHub/local-plan-extractor/dataset/existing-platform-datasets-dec25/local-plan.csv')

## Individual spreadsheets

In [34]:
old_df.head()

,dataset,end-date,entity,entry-date,geojson,geometry,name,organisation-entity,point,prefix,...,document-url,documentation-url,local-plan-boundary,local-plan-process,local-planning-authorities,notes,organisation,organisations,period-end-date,period-start-date
0,local-plan,NaN,4220000,2024-10-02,NaN,NaN,Arun District Council Local Plan 2011 - 2031,600001,NaN,local-plan,...,NaN,https://www.arun.gov.uk/adopted-local-plan/,E07000224,NaN,NaN,NaN,NaN,local-authority:ARU,2031-01-01,2011-01-01
1,local-plan,NaN,4220001,2024-10-02,NaN,NaN,London Borough of Islington Local Plan 2023,600001,NaN,local-plan,...,NaN,https://www.islington.gov.uk/planning/planning...,E09000019,NaN,NaN,NaN,NaN,local-authority:ISL,2037-01-01,2020-01-01
2,local-plan,NaN,4220002,2024-10-15,NaN,NaN,Camden local plan 2026,600001,NaN,local-plan,...,NaN,https://www.camden.gov.uk/draft-new-local-plan,E09000007,NaN,NaN,NaN,NaN,local-authority:CMD,2041-01-01,2026-01-01
3,local-plan,NaN,4220003,2024-10-02,NaN,NaN,Darlington Local Plan 2016 - 2036,600001,NaN,local-plan,...,NaN,https://www.darlington.gov.uk/environment-and-...,E06000005,NaN,NaN,NaN,NaN,local-authority:DAL,2036-01-01,2016-01-01
4,local-plan,NaN,4220004,2024-10-02,NaN,NaN,East Lindsey Local Plan Core Strategy,600001,NaN,local-plan,...,NaN,https://www.e-lindsey.gov.uk/article/8934/Adop...,E07000137,NaN,NaN,NaN,NaN,local-authority:ELI,2031-01-01,2016-01-01

In [42]:
old_df.loc[old_df['organisations']=='local-authority:ADU']

,dataset,end-date,entity,entry-date,geojson,geometry,name,organisation-entity,point,prefix,...,document-url,documentation-url,local-plan-boundary,local-plan-process,local-planning-authorities,notes,organisation,organisations,period-end-date,period-start-date
10,local-plan,NaN,4220010,2024-10-02,NaN,NaN,Adur District Council Local Plan 2017,600001,NaN,local-plan,...,NaN,https://www.adur-worthing.gov.uk/adur-local-plan/,E07000223,NaN,NaN,NaN,NaN,local-authority:ADU,2032-01-01,2017-01-01
11,local-plan,NaN,4220011,2024-10-21,NaN,NaN,Adur Local Plan 2017 (adopted) - Part 1,600001,NaN,local-plan,...,NaN,https://www.adur-worthing.gov.uk/adur-local-plan,E07000223,NaN,NaN,NaN,NaN,local-authority:ADU,2032-01-01,2011-01-01

In [44]:
my_df.loc[my_df['local-planning-authorities']=='local-authority:ADU']

,entity,reference,name,dataset,period-start-date,period-end-date,local-planning-authorities,mineral-planning-authorities,waste-planning-authorities,local-plan-process,documentation-url,document-url,entry-date,start-date,end-date,notes
412,4220412,adur-district-council-local-plan-2017,Adur Local Plan 2017,local-plan,NaN,2032.0,local-authority:ADU,NaN,NaN,adopted,https://www.adur-worthing.gov.uk/adur-local-plan/,"https://www.adur-worthing.gov.uk/media/Media,1...",2025-12-04,NaN,NaN,NaN

---

In [ ]:
old_df.loc[old_df['organisations']=='local-authority:ADU']

,dataset,end-date,entity,entry-date,geojson,geometry,name,organisation-entity,point,prefix,...,document-url,documentation-url,local-plan-boundary,local-plan-process,local-planning-authorities,notes,organisation,organisations,period-end-date,period-start-date
10,local-plan,NaN,4220010,2024-10-02,NaN,NaN,Adur District Council Local Plan 2017,600001,NaN,local-plan,...,NaN,https://www.adur-worthing.gov.uk/adur-local-plan/,E07000223,NaN,NaN,NaN,NaN,local-authority:ADU,2032-01-01,2017-01-01
11,local-plan,NaN,4220011,2024-10-21,NaN,NaN,Adur Local Plan 2017 (adopted) - Part 1,600001,NaN,local-plan,...,NaN,https://www.adur-worthing.gov.uk/adur-local-plan,E07000223,NaN,NaN,NaN,NaN,local-authority:ADU,2032-01-01,2011-01-01

In [ ]:
my_df.loc[my_df['local-planning-authorities']=='local-authority:ADU']

,entity,reference,name,dataset,period-start-date,period-end-date,local-planning-authorities,mineral-planning-authorities,waste-planning-authorities,local-plan-process,documentation-url,document-url,entry-date,start-date,end-date,notes
412,4220412,adur-district-council-local-plan-2017,Adur Local Plan 2017,local-plan,NaN,2032.0,local-authority:ADU,NaN,NaN,adopted,https://www.adur-worthing.gov.uk/adur-local-plan/,"https://www.adur-worthing.gov.uk/media/Media,1...",2025-12-04,NaN,NaN,NaN

## Merging them together

In [21]:
merged = pd.merge(old_df[['reference', 'organisations']], my_df[['reference', 'local-planning-authorities']], on='reference', how='outer', indicator=True)

In [22]:
merged['_merge'].value_counts()

_merge
right_only    629
left_only     135
both           17
Name: count, dtype: int64

In [25]:
merged.rename(columns={'local-planning-authorities':'my_work', 'organisations':'old_work'}).loc[merged['_merge'] =='both']

,reference,old_work,my_work,_merge
0,adur-district-council-local-plan-2017,local-authority:ADU,local-authority:ADU,both
17,ashford-borough-council-local-plan-2019,local-authority:ASF,local-authority:ASF,both
21,babergh-district-council-local-plan-2023,local-authority:BAB;local-authority:MSU,local-authority:BAB;local-authority:MSU,both
24,barnsley-metropolitan-borough-council-local-pl...,local-authority:BNS,local-authority:BNS,both
44,blaby-district-council-local-plan-2019,local-authority:BLA,local-authority:BLA,both
55,bolton-metropolitan-borough-council-local-plan...,local-authority:BOL,local-authority:BOL,both
73,breckland-district-council-local-plan-2023,local-authority:BRE,local-authority:BRE,both
116,cambridge-city-council-local-plan-2018,local-authority:CAB,local-authority:CAB,both
126,castle-point-borough-council-local-plan-1998,local-authority:CAS,local-authority:CAS,both
164,city-of-london-corporation-local-plan-2015,local-authority:LND,local-authority:LND,both
194,dartford-borough-council-local-plan-2024,local-authority:DAR,local-authority:DAR,both
375,london-borough-of-bromley-local-plan-2019,local-authority:BRY,local-authority:BRY,both
379,london-borough-of-camden-local-plan-2017,local-authority:CMD,local-authority:CMD,both
408,london-borough-of-islington-local-plan-2023,local-authority:ISL,local-authority:ISL,both
430,london-borough-of-sutton-local-plan-2018,local-authority:STN,local-authority:STN,both
441,maidstone-borough-council-local-plan-2021,local-authority:MAI,local-authority:MAI,both
715,vale-of-white-horse-district-council-local-pla...,local-authority:VAL,local-authority:VAL,both