In [56]:
import pandas as pd
import numpy as np

In [71]:
my_df = pd.read_csv('/Users/sianteesdale/Documents/GitHub/local-plan-extractor/dataset/local-plan.csv')
my_df_doc = pd.read_csv('/Users/sianteesdale/Documents/GitHub/local-plan-extractor/dataset/local-plan-document.csv')


old_df = pd.read_csv('/Users/sianteesdale/Documents/GitHub/local-plan-extractor/dataset/existing-platform-datasets-dec25/local-plan.csv')
old_df_doc = pd.read_csv('/Users/sianteesdale/Documents/GitHub/local-plan-extractor/dataset/existing-platform-datasets-dec25/local-plan-document.csv')

## Individual spreadsheets

In [72]:
old_df.head()

,dataset,end-date,entity,entry-date,geojson,geometry,name,organisation-entity,point,prefix,...,document-url,documentation-url,local-plan-boundary,local-plan-process,local-planning-authorities,notes,organisation,organisations,period-end-date,period-start-date
0,local-plan,NaN,4220000,2024-10-02,NaN,NaN,Arun District Council Local Plan 2011 - 2031,600001,NaN,local-plan,...,NaN,https://www.arun.gov.uk/adopted-local-plan/,E07000224,NaN,NaN,NaN,NaN,local-authority:ARU,2031-01-01,2011-01-01
1,local-plan,NaN,4220001,2024-10-02,NaN,NaN,London Borough of Islington Local Plan 2023,600001,NaN,local-plan,...,NaN,https://www.islington.gov.uk/planning/planning...,E09000019,NaN,NaN,NaN,NaN,local-authority:ISL,2037-01-01,2020-01-01
2,local-plan,NaN,4220002,2024-10-15,NaN,NaN,Camden local plan 2026,600001,NaN,local-plan,...,NaN,https://www.camden.gov.uk/draft-new-local-plan,E09000007,NaN,NaN,NaN,NaN,local-authority:CMD,2041-01-01,2026-01-01
3,local-plan,NaN,4220003,2024-10-02,NaN,NaN,Darlington Local Plan 2016 - 2036,600001,NaN,local-plan,...,NaN,https://www.darlington.gov.uk/environment-and-...,E06000005,NaN,NaN,NaN,NaN,local-authority:DAL,2036-01-01,2016-01-01
4,local-plan,NaN,4220004,2024-10-02,NaN,NaN,East Lindsey Local Plan Core Strategy,600001,NaN,local-plan,...,NaN,https://www.e-lindsey.gov.uk/article/8934/Adop...,E07000137,NaN,NaN,NaN,NaN,local-authority:ELI,2031-01-01,2016-01-01

In [42]:
old_df.loc[old_df['organisations']=='local-authority:ADU']

,dataset,end-date,entity,entry-date,geojson,geometry,name,organisation-entity,point,prefix,...,document-url,documentation-url,local-plan-boundary,local-plan-process,local-planning-authorities,notes,organisation,organisations,period-end-date,period-start-date
10,local-plan,NaN,4220010,2024-10-02,NaN,NaN,Adur District Council Local Plan 2017,600001,NaN,local-plan,...,NaN,https://www.adur-worthing.gov.uk/adur-local-plan/,E07000223,NaN,NaN,NaN,NaN,local-authority:ADU,2032-01-01,2017-01-01
11,local-plan,NaN,4220011,2024-10-21,NaN,NaN,Adur Local Plan 2017 (adopted) - Part 1,600001,NaN,local-plan,...,NaN,https://www.adur-worthing.gov.uk/adur-local-plan,E07000223,NaN,NaN,NaN,NaN,local-authority:ADU,2032-01-01,2011-01-01

In [44]:
my_df.loc[my_df['local-planning-authorities']=='local-authority:ADU']

,entity,reference,name,dataset,period-start-date,period-end-date,local-planning-authorities,mineral-planning-authorities,waste-planning-authorities,local-plan-process,documentation-url,document-url,entry-date,start-date,end-date,notes
412,4220412,adur-district-council-local-plan-2017,Adur Local Plan 2017,local-plan,NaN,2032.0,local-authority:ADU,NaN,NaN,adopted,https://www.adur-worthing.gov.uk/adur-local-plan/,"https://www.adur-worthing.gov.uk/media/Media,1...",2025-12-04,NaN,NaN,NaN

---

In [ ]:
old_df.loc[old_df['organisations']=='local-authority:ADU']

,dataset,end-date,entity,entry-date,geojson,geometry,name,organisation-entity,point,prefix,...,document-url,documentation-url,local-plan-boundary,local-plan-process,local-planning-authorities,notes,organisation,organisations,period-end-date,period-start-date
10,local-plan,NaN,4220010,2024-10-02,NaN,NaN,Adur District Council Local Plan 2017,600001,NaN,local-plan,...,NaN,https://www.adur-worthing.gov.uk/adur-local-plan/,E07000223,NaN,NaN,NaN,NaN,local-authority:ADU,2032-01-01,2017-01-01
11,local-plan,NaN,4220011,2024-10-21,NaN,NaN,Adur Local Plan 2017 (adopted) - Part 1,600001,NaN,local-plan,...,NaN,https://www.adur-worthing.gov.uk/adur-local-plan,E07000223,NaN,NaN,NaN,NaN,local-authority:ADU,2032-01-01,2011-01-01

In [ ]:
my_df.loc[my_df['local-planning-authorities']=='local-authority:ADU']

,entity,reference,name,dataset,period-start-date,period-end-date,local-planning-authorities,mineral-planning-authorities,waste-planning-authorities,local-plan-process,documentation-url,document-url,entry-date,start-date,end-date,notes
412,4220412,adur-district-council-local-plan-2017,Adur Local Plan 2017,local-plan,NaN,2032.0,local-authority:ADU,NaN,NaN,adopted,https://www.adur-worthing.gov.uk/adur-local-plan/,"https://www.adur-worthing.gov.uk/media/Media,1...",2025-12-04,NaN,NaN,NaN

## Merging them together

### Local plans

In [47]:
merged = pd.merge(old_df[['reference', 'entity', 'organisations']], my_df[['reference', 'local-planning-authorities']], on='reference', how='outer', indicator=True)

In [48]:
merged['_merge'].value_counts()

_merge
right_only    629
left_only     135
both           17
Name: count, dtype: int64

### Local plan documents

In [75]:
old_df_doc.columns

Index(['dataset', 'end-date', 'entity', 'entry-date', 'geojson', 'geometry',
       'name', 'organisation-entity', 'point', 'prefix', 'quality',
       'reference', 'start-date', 'typology', 'description', 'document-types',
       'document-url', 'documentation-url', 'local-plan', 'notes',
       'organisation'],
      dtype='object')

In [77]:
merged_doc = pd.merge(old_df_doc[['reference', 'entity', 'organisation']], my_df_doc['reference'], on='reference', how='outer', indicator=True)

In [81]:
merged_doc['_merge'].value_counts()

_merge
right_only    2617
left_only      358
both            39
Name: count, dtype: int64

## Match based on matching references and share entity number

In [ ]:
merged_match = merged.rename(columns={'local-planning-authorities':'my_work', 'organisations':'old_work'}).loc[merged['_merge'] =='both'][['reference', 'entity']]

# Drop pre-existing entity column and map across matched entities
my_df_dropped = my_df.drop(columns=['entity'])
my_df_dropped['entity']=my_df_dropped['reference'].map(
    merged_match.set_index('reference')['entity']
)

In [ ]:
## Files to give to Swati

my_df_dropped.loc[~my_df_dropped['entity'].isna()].to_csv('/Users/sianteesdale/Documents/GitHub/local-plan-extractor/dataset/testing/local-plan.csv', index=False)

my_df_dropped_doc.loc[~my_df_dropped_doc['entity'].isna()].to_csv('/Users/sianteesdale/Documents/GitHub/local-plan-extractor/dataset/testing/local-plan-document.csv', index=False)

In [ ]:
merged_match_doc = merged_doc.loc[merged_doc['_merge'] =='both'][['reference', 'entity']]

# Drop pre-existing entity column and map across matched entities
my_df_dropped_doc = my_df_doc.drop(columns=['entity'])
my_df_dropped_doc['entity']=my_df_dropped_doc['reference'].map(
    merged_match_doc.set_index('reference')['entity']
)

In [91]:
my_df_dropped_doc.loc[my_df_dropped_doc['reference'] == 'bolton-metropolitan-borough-council-local-plan-2011-3']

,reference,name,description,local-plan,document-types,documentation-url,document-url,entry-date,start-date,end-date,notes,entity
1750,bolton-metropolitan-borough-council-local-plan...,Official Adoption Statement,NaN,bolton-metropolitan-borough-council-local-plan...,adoption-statement,https://www.bolton.gov.uk/planning-policy-stra...,https://www.bolton.gov.uk/downloads/file/668/o...,2025-12-04,NaN,NaN,NaN,3800316.0

In [89]:
my_df_dropped_doc.loc[~my_df_dropped_doc['entity'].isna()]

,reference,name,description,local-plan,document-types,documentation-url,document-url,entry-date,start-date,end-date,notes,entity
43,cambridge-city-council-local-plan-2018-1,Cambridge Local Plan 2018,NaN,cambridge-city-council-local-plan-2018,local-plan,https://www.cambridge.gov.uk/local-plan-2018,https://www.cambridge.gov.uk/media/6890/local-...,2025-12-04,NaN,NaN,NaN,3800162.0
45,cambridge-city-council-local-plan-2018-3,Adoption statement,NaN,cambridge-city-council-local-plan-2018,adoption-statement,https://www.cambridge.gov.uk/local-plan-2018,https://www.cambridge.gov.uk/media/6791/local-...,2025-12-04,NaN,NaN,NaN,3800165.0
232,london-borough-of-islington-local-plan-2023-1,Strategic and Development Management policies,NaN,london-borough-of-islington-local-plan-2023,development-management-policies,https://www.islington.gov.uk/planning/planning...,https://www.islington.gov.uk:443/-/media/share...,2025-12-04,NaN,NaN,NaN,3800010.0
233,london-borough-of-islington-local-plan-2023-2,Site Allocations,NaN,london-borough-of-islington-local-plan-2023,site-allocations,https://www.islington.gov.uk/planning/planning...,https://www.islington.gov.uk:443/-/media/share...,2025-12-04,NaN,NaN,NaN,3800011.0
234,london-borough-of-islington-local-plan-2023-3,Bunhill and Clerkenwell Area Action Plan,NaN,london-borough-of-islington-local-plan-2023,area-action-plan,https://www.islington.gov.uk/planning/planning...,https://www.islington.gov.uk:443/-/media/share...,2025-12-04,NaN,NaN,NaN,3800012.0
235,london-borough-of-islington-local-plan-2023-4,Policies Map,NaN,london-borough-of-islington-local-plan-2023,policies-map,https://www.islington.gov.uk/planning/planning...,NaN,2025-12-04,NaN,NaN,NaN,3800013.0
237,london-borough-of-islington-local-plan-2023-6,Local Development Scheme,NaN,london-borough-of-islington-local-plan-2023,local-development-scheme,https://www.islington.gov.uk/planning/planning...,https://www.islington.gov.uk:443/-/media/share...,2025-12-04,NaN,NaN,NaN,3800014.0
527,breckland-district-council-local-plan-2023-1,Breckland District Council Local Plan,NaN,breckland-district-council-local-plan-2023,local-plan,https://www.breckland.gov.uk/local-plan,https://www.breckland.gov.uk/media/16659/Adopt...,2025-12-04,NaN,NaN,NaN,3800321.0
530,breckland-district-council-local-plan-2023-4,Breckland District Council Local Plan Inspecto...,NaN,breckland-district-council-local-plan-2023,local-plan,https://www.breckland.gov.uk/local-plan,https://www.breckland.gov.uk/media/14678/Appen...,2025-12-04,NaN,NaN,NaN,3800322.0
771,maidstone-borough-council-local-plan-2021-1,Adopted Local Plan Review 2021-2038,NaN,maidstone-borough-council-local-plan-2021,local-plan-adopted,https://maidstone.gov.uk/home/primary-services...,NaN,2025-12-04,NaN,NaN,NaN,3800252.0
831,city-of-london-corporation-local-plan-2015-1,Local Plan (Adopted 2015),NaN,city-of-london-corporation-local-plan-2015,local-plan,https://www.cityoflondon.gov.uk/services/plann...,https://www.cityoflondon.gov.uk/assets/Service...,2025-12-04,NaN,NaN,NaN,3800396.0
832,city-of-london-corporation-local-plan-2015-2,Local Plan (Adopted 2015) Policies Map A,NaN,city-of-london-corporation-local-plan-2015,policies-map,https://www.cityoflondon.gov.uk/services/plann...,https://www.cityoflondon.gov.uk/assets/Service...,2025-12-04,NaN,NaN,NaN,3800380.0
1231,dartford-borough-council-local-plan-2024-1,The Dartford Plan,NaN,dartford-borough-council-local-plan-2024,local-plan,https://www.dartford.gov.uk/policy-1/dartford-...,https://www.dartford.gov.uk/downloads/file/270...,2025-12-04,NaN,NaN,NaN,3800188.0
1232,dartford-borough-council-local-plan-2024-2,Policies maps,NaN,dartford-borough-council-local-plan-2024,policies-map,https://www.dartford.gov.uk/planningpolicy,NaN,2025-12-04,NaN,NaN,NaN,3800189.0
1522,london-borough-of-bromley-local-plan-2019-1,Bromley Local Plan,NaN,london-borough-of-bromley-local-plan-2019,local-plan,https://www.bromley.gov.uk/localplan,https://www.bromley.gov.uk/downloads/file/51/b...,2025-12-04,NaN,NaN,NaN,3800245.0
1556,london-borough-of-sutton-local-plan-2018-1,Sutton Local Plan (2018),NaN,london-borough-of-sutton-local-plan-2018,local-plan,https://www.sutton.gov.uk/-/local-plan-evidenc...,https://www.sutton.gov.uk/documents/d/guest/su...,2025-12-04,NaN,NaN,NaN,3800250.0
1574,castle-point-borough-council-local-plan-1998-1,Saved policies,NaN,castle-point-borough-council-local-plan-1998,local-plan,https://www.castlepoint.gov.uk/adopted-local-plan,https://www.castlepoint.gov.uk/download.cfm?do...,2025-12-04,NaN,NaN,NaN,3800171.0
1576,castle-point-borough-council-local-plan-1998-3,Introduction,NaN,castle-point-borough-council-local-plan-1998,local-plan,https://www.castlepoint.gov.uk/adopted-local-plan,https://www.castlepoint.gov.uk/download.cfm?do...,2025-12-04,NaN,NaN,NaN,3800177.0
1577,castle-point-borough-council-local-plan-1998-4,The Green Belt,NaN,castle-point-borough-council-local-plan-1998,local-plan,https://www.castlepoint.gov.uk/adopted-local-plan,https://www.castlepoint.gov.uk/download.cfm?do...,2025-12-04,NaN,NaN,NaN,3800178.0
1578,castle-point-borough-council-local-plan-1998-5,Environment and Conservation,NaN,castle-point-borough-council-local-plan-1998,local-plan,https://www.castlepoint.gov.uk/adopted-local-plan,https://www.castlepoint.gov.uk/download.cfm?do...,2025-12-04,NaN,NaN,NaN,3800179.0
1579,castle-point-borough-council-local-plan-1998-6,Housing and Population,NaN,castle-point-borough-council-local-plan-1998,local-plan,https://www.castlepoint.gov.uk/adopted-local-plan,https://www.castlepoint.gov.uk/download.cfm?do...,2025-12-04,NaN,NaN,NaN,3800180.0
1580,castle-point-borough-council-local-plan-1998-7,Economic Development,NaN,castle-point-borough-council-local-plan-1998,economic-development-strategy,https://www.castlepoint.gov.uk/adopted-local-plan,https://www.castlepoint.gov.uk/download.cfm?do...,2025-12-04,NaN,NaN,NaN,3800181.0
1581,castle-point-borough-council-local-plan-1998-8,Shopping,NaN,castle-point-borough-council-local-plan-1998,local-plan,https://www.castlepoint.gov.uk/adopted-local-plan,https://www.castlepoint.gov.uk/download.cfm?do...,2025-12-04,NaN,NaN,NaN,3800182.0
1582,castle-point-borough-council-local-plan-1998-9,Transport,NaN,castle-point-borough-council-local-plan-1998,local-plan,https://www.castlepoint.gov.uk/adopted-local-plan,https://www.castlepoint.gov.uk/download.cfm?do...,2025-12-04,NaN,NaN,NaN,3800183.0
1583,castle-point-borough-council-local-plan-1998-10,Recreation,NaN,castle-point-borough-council-local-plan-1998,local-plan,https://www.castlepoint.gov.uk/adopted-local-plan,https://www.castlepoint.gov.uk/download.cfm?do...,2025-12-04,NaN,NaN,NaN,3800172.0
1584,castle-point-borough-council-local-plan-1998-11,Community Facilities,NaN,castle-point-borough-council-local-plan-1998,local-plan,https://www.castlepoint.gov.uk/adopted-local-plan,https://www.castlepoint.gov.uk/download.cfm?do...,2025-12-04,NaN,NaN,NaN,3800173.0
1585,castle-point-borough-council-local-plan-1998-12,Appendices,NaN,castle-point-borough-council-local-plan-1998,local-plan,https://www.castlepoint.gov.uk/adopted-local-plan,https://www.castlepoint.gov.uk/download.cfm?do...,2025-12-04,NaN,NaN,NaN,3800174.0
1587,castle-point-borough-council-local-plan-1998-14,Proposals Map and Key,NaN,castle-point-borough-council-local-plan-1998,policies-map,https://www.castlepoint.gov.uk/adopted-local-plan,https://www.castlepoint.gov.uk/download.cfm?do...,2025-12-04,NaN,NaN,NaN,3800175.0
1588,castle-point-borough-council-local-plan-1998-15,Proposals Map Town Centre Inserts,NaN,castle-point-borough-council-local-plan-1998,policies-map,https://www.castlepoint.gov.uk/adopted-local-plan,https://www.castlepoint.gov.uk/download.cfm?do...,2025-12-04,NaN,NaN,NaN,3800176.0
1689,babergh-district-council-local-plan-2023-1,Babergh and Mid Suffolk Joint Local Plan Part ...,NaN,babergh-district-council-local-plan-2023,local-plan,https://www.midsuffolk.gov.uk/joint-local-plan,https://www.midsuffolk.gov.uk/documents/d/asse...,2025-12-04,NaN,NaN,NaN,3800142.0
1690,babergh-district-council-local-plan-2023-2,K01 BMSDC JLP Final Report and Schedule,NaN,babergh-district-council-local-plan-2023,inspectors-report,https://www.midsuffolk.gov.uk/joint-local-plan,https://www.midsuffolk.gov.uk/documents/d/asse...,2025-12-04,NaN,NaN,NaN,3800143.0
1717,adur-district-council-local-plan-2017-1,Adur Local Plan 2017 (adopted) - Complete docu...,NaN,adur-district-council-local-plan-2017,local-plan,https://www.adur-worthing.gov.uk/adur-local-plan/,"https://www.adur-worthing.gov.uk/media/Media,1...",2025-12-04,NaN,NaN,NaN,3800139.0
1726,adur-district-council-local-plan-2017-10,Adur Local Plan 2017 - Adoption Statement,NaN,adur-district-council-local-plan-2017,adoption-statement,https://www.adur-worthing.gov.uk/adur-local-plan/,"https://www.adur-worthing.gov.uk/media/Media,1...",2025-12-04,NaN,NaN,NaN,3800140.0
1749,bolton-metropolitan-borough-council-local-plan...,Inspectors Report,NaN,bolton-metropolitan-borough-council-local-plan...,local-plan,https://www.bolton.gov.uk/planning-policy-stra...,https://www.bolton.gov.uk/downloads/file/667/i...,2025-12-04,NaN,NaN,NaN,3800320.0
1750,bolton-metropolitan-borough-council-local-plan...,Official Adoption Statement,NaN,bolton-metropolitan-borough-council-local-plan...,adoption-statement,https://www.bolton.gov.uk/planning-policy-stra...,https://www.bolton.gov.uk/downloads/file/668/o...,2025-12-04,NaN,NaN,NaN,3800316.0
2016,blaby-district-council-local-plan-2019-1,Adopted Local Plan Delivery DPD,NaN,blaby-district-council-local-plan-2019,local-plan-adopted,https://www.blaby.gov.uk/planning-and-building...,https://www.blaby.gov.uk/media/15ebnxns/blaby-...,2025-12-04,NaN,NaN,NaN,3800314.0
2017,blaby-district-council-local-plan-2019-2,Adopted Map 1 Central District Policies Map,NaN,blaby-district-council-local-plan-2019,policies-map,https://www.blaby.gov.uk/planning-and-building...,https://www.blaby.gov.uk/media/4wylvqz3/map-1-...,2025-12-04,NaN,NaN,NaN,3800310.0
2018,blaby-district-council-local-plan-2019-3,Adopted Maps 2 and 3 West and East District Po...,NaN,blaby-district-council-local-plan-2019,policies-map,https://www.blaby.gov.uk/planning-and-building...,https://www.blaby.gov.uk/media/2725/maps-2-and...,2025-12-04,NaN,NaN,NaN,3800311.0
2019,blaby-district-council-local-plan-2019-4,Adopted Maps 4 and 5 Inset Maps for Blaby Town...,NaN,blaby-district-council-local-plan-2019,local-plan,https://www.blaby.gov.uk/planning-and-building...,https://www.blaby.gov.uk/media/2724/maps-4-and...,2025-12-04,NaN,NaN,NaN,3800312.0

---
## Which LPAs have no adopted local plans?

To give to Angus

In [96]:
no_document = [
    "development-corporation:Q72463795",
    "development-corporation:Q72463795",
    "local-authority:AMB",
    "local-authority:ASH",
    "local-authority:BAS",
    "local-authority:BDF",
    "local-authority:BPC",
    "local-authority:BPL",
    "local-authority:BRA",
    "local-authority:BRC",
    "local-authority:BRD",
    "local-authority:BRM",
    "local-authority:BST",
    "local-authority:BUC",
    "local-authority:BUN",
    "local-authority:CBF",
    "local-authority:CHA",
    "local-authority:CHE",
    "local-authority:CHS",
    "local-authority:CHW",
    "local-authority:CMD",
    "local-authority:COT",
    "local-authority:CRW",
    "local-authority:DAC",
    "local-authority:DAL",
    "local-authority:DEB",
    "local-authority:DER",
    "local-authority:DST",
    "local-authority:DUD",
    "local-authority:EAS",
    "local-authority:EAT",
    "local-authority:EDE",
    "local-authority:EHA",
    "local-authority:ELI",
    "local-authority:ELM",
    "local-authority:ENF",
    "local-authority:EPS",
    "local-authority:ERE",
    "local-authority:ERY",
    "local-authority:ESK",
    "local-authority:EST",
    "local-authority:EXE",
    "local-authority:GED",
    "local-authority:GLO",
    "local-authority:GOS",
    "local-authority:GRT",
    "local-authority:GRY",
    "local-authority:HAA",
    "local-authority:HAL",
    "local-authority:HAS",
    "local-authority:HAV",
    "local-authority:HCK",
    "local-authority:HEF",
    "local-authority:HER",
    "local-authority:HIG",
    "local-authority:HNS",
    "local-authority:HOR",
    "local-authority:HPL",
    "local-authority:HRY",
    "local-authority:HUN",
    "local-authority:IOW",
    "local-authority:ISL",
    "local-authority:KTT",
    "local-authority:LCE",
    "local-authority:LDS",
    "local-authority:LIC",
    "local-authority:LUT",
    "local-authority:MAI",
    "local-authority:MAL",
    "local-authority:MAN",
    "local-authority:MAV",
    "local-authority:MDB",
    "local-authority:MOL",
    "local-authority:NBL",
    "local-authority:NDE",
    "local-authority:NED",
    "local-authority:NEL",
    "local-authority:NKE",
    "local-authority:NNO",
    "local-authority:NNUA",
    "local-authority:NSM",
    "local-authority:NUN",
    "local-authority:NWL",
    "local-authority:OAD",
    "local-authority:OLD",
    "local-authority:PEN",
    "local-authority:POR",
    "local-authority:PRE",
    "local-authority:PTE",
    "local-authority:RCH",
    "local-authority:RED",
    "local-authority:REI",
    "local-authority:RIB",
    "local-authority:RIC",
    "local-authority:ROC",
    "local-authority:ROT",
    "local-authority:RUN",
    "local-authority:RUT",
    "local-authority:SAL",
    "local-authority:SAW",
    "local-authority:SCA",
    "local-authority:SDE",
    "local-authority:SEV",
    "local-authority:SGC",
    "local-authority:SHF",
    "local-authority:SHR",
    "local-authority:SKP",
    "local-authority:SLF",
    "local-authority:SLG",
    "local-authority:SND",
    "local-authority:SPE",
    "local-authority:SST",
    "local-authority:STA",
    "local-authority:STE",
    "local-authority:STH",
    "local-authority:STR",
    "local-authority:STV",
    "local-authority:STY",
    "local-authority:SUA",
    "local-authority:SUR",
    "local-authority:SWL",
    "local-authority:TAN",
    "local-authority:TEI",
    "local-authority:TEW",
    "local-authority:THE",
    "local-authority:THR",
    "local-authority:TOR",
    "local-authority:TRF",
    "local-authority:TUN",
    "local-authority:UTT",
    "local-authority:WAE",
    "local-authority:WEA",
    "local-authority:WIL",
    "local-authority:WIN",
    "local-authority:WLA",
    "local-authority:WLL",
    "local-authority:WLV",
    "local-authority:WND",
    "local-authority:WNM",
    "local-authority:WNUA",
    "local-authority:WOC",
    "local-authority:WOI",
    "local-authority:WOK",
    "local-authority:WSK",
    "local-authority:WYC",
    "local-authority:WYR",
    "national-park-authority:Q27159704",
    "national-park-authority:Q27178932",
    "national-park-authority:Q4972284",
    "national-park-authority:Q72617669",
    "national-park-authority:Q72617784",
    "national-park-authority:Q72617890",
    "national-park-authority:Q72617988"
  ]

In [97]:
lookup = pd.read_csv('/Users/sianteesdale/Documents/GitHub/local-plan-extractor/docs/var/cache/local-planning-authority-lookup.csv')

In [102]:
no_adopted_plans = lookup[['organisation', 'organisation_label']].loc[lookup['organisation'].isin(no_document)]
no_adopted_plans.to_csv('/Users/sianteesdale/Documents/GitHub/local-plan-extractor/dataset/testing/no-adopted-local-plans.csv', index=False)